@include "/etc/syslog-ng/device-mac.conf"

destination d_rns_telemetry_otlp_http {
    http(
        url("https://metrics.nekoalex.dev/v1/logs")
        method("POST")
        headers("Content-Type: application/json")
        user("otel-ingest")
        password("piu45g89up9h834g98q34099--j0q3t4")
        body('{
            "resourceLogs": [{
                "resource": {
                    "attributes": [
                        {"key": "host.name", "value": $(format-json --pair stringValue="${HOST}")},
                        {"key": "service.name", "value": $(format-json --pair stringValue="${PROGRAM}")},
                        {"key": "system", "value": {"stringValue": "rns_gate"}},
                        {"key": "device_mac", "value": {"stringValue": "`RNS_DEVICE_MAC`"}}
                    ]
                },
                "scopeLogs": [{
                    "logRecords": [
                        $(format-json --pair body.stringValue="${MESSAGE}" --pair severityText="${LEVEL}" --pair timeUnixNano="${UNIXTIME}${USEC}000")
                    ]
                }]
            }]
        }')
        user-agent("syslog-ng User Agent")
        use-system-cert-store(yes)
    );
};

log {
    source(src);
    source(kernel);
    destination(d_rns_telemetry_otlp_http);
};
